<?php if (!$posts): ?>
    <p>Объявлений пока нет.</p>
<?php else: ?>
    <?php foreach ($posts as $post): ?>
        <article>
            <h2><?= htmlspecialchars($post->title) ?></h2>
            <div class="body"><?= htmlspecialchars($post->text) ?></div>
            <p>Телефон: <?= htmlspecialchars($post->phoneNumber) ?></p>
        </article>
    <?php endforeach ?>
<?php endif ?>


<form action="/?page=1" method="post">

    <input type="text" name="title" placeholder="Имя"/>
    <input type="text" name="phone-number" placeholder="Номер"//>
    <input type="text" name="text" placeholder="Текст"/>

    <button>Добавить</button>
</form>


